CREATE TABLE IF NOT EXISTS CREDIT_CARD (
    IDT_CREDIT_CARD SERIAL NOT NULL,
    IDT_CUSTOMER INT NOT NULL,
    IDT_ACCOUNT INT NOT NULL,
    DES_PRINTED_NAME VARCHAR(100) NOT NULL,
    NUM_LIMIT_CARD NUMERIC(12,2) NOT NULL,
    NUM_CREDIT_CARD VARCHAR(50) NOT NULL,
    NUM_CVV VARCHAR(50) NOT NULL,
    DAT_EXPIRATION TIMESTAMP NOT NULL,
    DES_STATUS VARCHAR(20),
    DAT_CREATE TIMESTAMP NOT NULL,
    DAT_UPDATE TIMESTAMP
);

ALTER TABLE CREDIT_CARD ADD CONSTRAINT creditcardpk PRIMARY KEY (IDT_CREDIT_CARD);
ALTER TABLE CREDIT_CARD ADD CONSTRAINT creditcardcustomerfk FOREIGN KEY (IDT_CUSTOMER) REFERENCES CUSTOMER(IDT_CUSTOMER);
ALTER TABLE CREDIT_CARD ADD CONSTRAINT creditcardaccountfk FOREIGN KEY (IDT_ACCOUNT) REFERENCES ACCOUNT(IDT_ACCOUNT);

COMMENT ON TABLE CREDIT_CARD IS 'Tabela de cartão de crédito';
COMMENT ON COLUMN CREDIT_CARD.IDT_CREDIT_CARD IS 'Identificação única do cartão';
COMMENT ON COLUMN CREDIT_CARD.IDT_CUSTOMER IS 'Identificação única do usuário';
COMMENT ON COLUMN CREDIT_CARD.IDT_ACCOUNT IS 'Identificação única da conta';
COMMENT ON COLUMN CREDIT_CARD.DES_PRINTED_NAME IS 'Nome impresso no cartão';
COMMENT ON COLUMN CREDIT_CARD.NUM_LIMIT_CARD IS 'Limite do cartão';
COMMENT ON COLUMN CREDIT_CARD.NUM_CREDIT_CARD IS 'Número do cartão de crédito';
COMMENT ON COLUMN CREDIT_CARD.NUM_CVV IS 'Número CVV do cartão';
COMMENT ON COLUMN CREDIT_CARD.DAT_EXPIRATION IS 'Data de expiração do cartão';
COMMENT ON COLUMN CREDIT_CARD.DES_STATUS IS 'Status do cartão';
COMMENT ON COLUMN CUSTOMER.DAT_CREATE IS 'Data de criação do registro';
COMMENT ON COLUMN CUSTOMER.DAT_UPDATE IS 'Data de atualização do registro';
